name: RC Release Docker

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  Release-AMD64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set RELEASE env var from package.json
        run: echo RELEASE=$(node --print "require('./package.json').rcVersion") >> $GITHUB_ENV

      - name: Fail if tag already exists
        run: '! docker manifest inspect ghcr.io/${{ github.repository }}:${{ env.RELEASE }}'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.RELEASE }}
